apiVersion: v1
kind: Secret # important for secret component
metadata:
  name: mongodb-secret # any name you choose
type: Opaque # default for arbitrary key-value pairs
data: # actual contents of the secret
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=

# Values must be base64 encoded
# Storing data in secret component doesnt automatically make it secure
# Built in mechanisms for encryption is not enabled by default

# To base64 encode a string: 
# https://stackoverflow.com/questions/37046771/base64-encode-string-command-line-windows
# cmd echo | set /p="username" | openssl base64 (if OpenSSL is installed)

# apply with
# kubectl apply -f mongo-secret.yaml

# get secret
# kubectl get secret