apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo # https://hub.docker.com/_/mongo for configuration and usage
          ports:
          - containerPort: 27017
          env: 
          - name: MONGO_INITDB_ROOT_USERNAME # required name for the container
            valueFrom:
              secretKeyRef:  
                name: mongodb-secret # from secret metadata
                key: mongo-root-username 
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:  
                name: mongodb-secret # from secret metadata
                key: mongo-root-password

# Deploy mongodb pod by
# kubectl apply -f mongo.yaml