apiVersion: v1
kind: ConfigMap # IMPORTANT: Defines component type..
metadata:
  name: mongodb-configmap # Can be any random name
data:  # Data, key-value pairs. no types!
  database_url: mongodb-service # service name, from mongo.yaml!