apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-class-name  # Referenced by the PVC
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4